apiVersion: v1
kind: Secret
metadata:
  name: academy-secrets
  namespace: ai-strategic-academy
type: Opaque
stringData:
  POSTGRES_USER: academy
  POSTGRES_PASSWORD: replace-with-internal-db-password
  POSTGRES_DB: academy
  DATABASE_URL: postgresql://academy:replace-with-internal-db-password@academy-postgres:5432/academy?schema=public
  NEXTAUTH_SECRET: replace-me
<<<<<<< HEAD
  GOOGLE_CLIENT_ID: replace-me
  GOOGLE_CLIENT_SECRET: replace-me
  GITHUB_CLIENT_ID: replace-me
  GITHUB_CLIENT_SECRET: replace-me
=======
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
>>>>>>> e63fa65c366d6aebc4d97c18216ba9069a19a7c2
